### ISSUE TITLE
Feature request: Add flight to iChun Morph

### ISSUE THREAD

**Issue by grydian** [allaryin/FairyFactions#20]
Any chance you could make it so when you morph into a fairy you can fly?  Thanks!

**Comment by allaryin** [comment]
There is no capability to morph into a fairy in the mod and probably never will be, it was one of the things Kodaichi explicitly stated he didn't want in his original plan, and I'd not only like to honor his original goal but also don't think it makes very much sense to add here. But if you carry a fairy on your head, you can jump long distances and fall without taking damage.

Additionally, MC 1.9 added wings, so in the future, there will be a vanilla method for flight.

**Comment by allaryin** [comment]
It has been brought to my attention that maybe you're referring to iChun's Morph mod? In that case, I'm all for him adding hooks to allow flight in that case - but I'm not in a position to add support for that on my end.

**Comment by allaryin** [comment]
It looks like this is simple enough - will PR him with that change right now.

**Comment by allaryin** [comment]
https://github.com/iChun/Morph/pull/805

**Comment by grydian** [comment]
Thanks thats exactly what I meant.  Sorry I was not more clear.  Thank you!
