### ISSUE TITLE
Fairy entity registration

### ISSUE THREAD

**Issue by Zarzuf** [allaryin/FairyFactions#24]
Hi :)

First of all thank you for porting this wonderful mod to minecraft 1.7.10 :)

Second, I noticed that the mod conflicts with Orespawn: they both add a mob simply called "fairy" and this causes Forge to crash.
Is there a chance you can change the name to something not conflicting like "fairymod.fairy" ?

**Comment by allaryin** [comment]
Huh? I... was fairly certain I was doing precisely that because I knew other mods added fairies... checking this out in further detail.

**Comment by allaryin** [comment]
Works for me... make sure you're using a current build of the mod? Old revs did not register the entity safely.

![2016-03-10_08 58 37](https://cloud.githubusercontent.com/assets/56085/13673378/55d4330e-e69e-11e5-98a3-c92b4906a212.png)
