### ISSUE TITLE
Implement rename GUI

### ISSUE THREAD

**Issue by allaryin** [allaryin/FairyFactions#3]
While most of the support code for renaming fairies should be in place, there is currently no gui implemented for it.

**Comment by danbornside** [comment]
Is there a reason this needs a separate gui? are nametags bad?

**Comment by allaryin** [comment]
Nametags are evil :) They're not craftable by default. Besides, we're going for implementing 100% of the original mod's capabilities, which included a simple rename ui. I'll probably knock that out tomorrow if I have the time.

**Comment by allaryin** [comment]
On server consumes the paper, makes the fairy sit down, but does not display the rename prompt.
