### ISSUE TITLE
Game crashed when loading

### ISSUE THREAD

**Issue by FuYang001** [allaryin/FairyFactions#34]
Game crashed after installing the newest version of FairFactions.
Crash report: https://pastebin.com/ttFJhz10

**Comment by kevin60667** [comment]
I also get the same problem.
[https://paste.ee/p/fcMOR](https://paste.ee/p/fcMOR)

**Comment by mrdrewlego** [comment]
I also get the same crash with a similar crash log.
https://pastebin.com/CPqQMNkj

**Comment by allaryin** [comment]
I'm re-creating my 1.7.10 dev environment now, will see what I can do on this today.

**Comment by allaryin** [comment]
I compiled this against forge 1558, but it looks like at least two of you are running 1614. I don't think there should be any incompatibility, but am starting my examination there.

**Comment by allaryin** [comment]
Found the issue, the jar available on Curse is corrupt. I've disabled that download and am uploading a new build that works, 0.5.2c (md5: 1d9f11f1b386db5e2eed146e21fbcb60).

![2018-06-06_13 12 24](https://user-images.githubusercontent.com/56085/41056937-4dda2998-698b-11e8-9249-f453f3c6ee42.png)
